[build]
publish = "public"
command = "hugo --gc --minify --debug"

[context.production.environment]
NODE_VERSION = "14.17.3"
NPM_VERSION = "6.14.13"
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"

# [context.split1]
# command = "hugo --gc --minify --enableGitInfo"

# [context.split1.environment]
# HUGO_VERSION = "0.86.0"
# HUGO_ENV = "production"

# [context.deploy-preview]
# command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# [context.deploy-preview.environment]
# HUGO_VERSION = "0.86.0"

# [context.branch-deploy]
# command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# [context.branch-deploy.environment]
# HUGO_VERSION = "0.86.0"

[context.next.environment]
NODE_VERSION = "14.17.3"
NPM_VERSION = "6.14.13"
HUGO_VERSION = "0.86.0"
HUGO_ENV = "next"
HUGO_ENABLEGITINFO = "true"
NODE_ENV = "production"
